version: "3"

services:
  setup:
    container_name: setup
    build:
      context: ./setup
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      GIN_MODE: release

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8081:8080"
    environment:
      PORT: 8080
      GIN_MODE: release

  frontend:
    container_name: frontend
    build:
      context: ./Client/app
    ports:
      - "80:3000"

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: db123
      POSTGRES_USER: nt_user
      POSTGRES_DB: nt_db

  adminer:
      image: adminer
      restart: always
      ports:
        - "8181:8181"