version: "3"

services:
  setup:
    container_name: setup
    build:
      context: ./setup
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      GIN_MODE: release
    networks:
      - nt-network

  authentication:
    container_name: authentication
    build:
      context: ./authentication
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      GIN_MODE: release
    networks:
      - nt-network

  transaction:
    container_name: transaction
    build:
      context: ./transaction
    ports:
      - "5433:5433"
    environment:
      PORT: 5433
      GIN_MODE: release
    networks:
      - nt-network

  engine:
    container_name: engine
    build:
      context: ./engine
    ports:
      - "8585:8585"
    environment:
      PORT: 8585
      GIN_MODE: release
    networks:
      - nt-network

  frontend:
    container_name: frontend
    build:
      context: ./client/app
    ports:
      - "3000:3000"
    networks:
      - nt-network

  database:
    container_name: database
    image: postgres:16-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: db123
      POSTGRES_USER: nt_user
      POSTGRES_DB: nt_db
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nt-network

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - setup
      - authentication
      - transaction
      - engine
      - database
    networks:
      - nt-network

networks:
  nt-network:
